version: "3.9"
    
services:
  db:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wp_html:/var/www/html

  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin:latest
    ports:
      - "8000:80"
    restart: always
    environment: 
      - PMA_HOST=db
      - PMA_ARBITRARY=1 
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress

volumes:
  wp_html:
    external: true
    name: docker-wordpress-starter_wordpress
  db_data:
    external: true
    name: docker-wordpress-starter_db_data